overrides:
  brace-expansion@^5.0.0: 5.0.9

allowBuilds:
  esbuild: true
  sharp: set this to true or false
  unrs-resolver: set this to true or false
  workerd: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
minimumReleaseAgeExclude:
  - miniflare@5.20260815.0-alpha
  - wrangler@4.124.0
